//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/22/2020 4:21:12 PM
namespace WSSPAAModel
{
    
    /// <summary>
    /// There are no comments for WSSPAAEntities1 in the schema.
    /// </summary>
    public partial class WSSPAAEntities1 : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new WSSPAAEntities1 object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WSSPAAEntities1(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Marks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Mark> Marks
        {
            get
            {
                if ((this._Marks == null))
                {
                    this._Marks = base.CreateQuery<Mark>("Marks");
                }
                return this._Marks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Mark> _Marks;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Student> _Students;
        /// <summary>
        /// There are no comments for Marks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMarks(Mark mark)
        {
            base.AddObject("Marks", mark);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WSSPAAModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><En" +
                "tityType Name=\"Mark\"><Key><PropertyRef Name=\"id\" /><PropertyRef Name=\"mark1\" /><" +
                "PropertyRef Name=\"subject\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" Nullable" +
                "=\"false\" /><Property Name=\"subject\" Type=\"Edm.String\" Nullable=\"false\" MaxLength" +
                "=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"mark1\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><NavigationProperty Name=\"Student\" Relationship=\"WSSPAAMod" +
                "el.FK_Marks_Student\" ToRole=\"Students\" FromRole=\"Marks\" /></EntityType><EntityTy" +
                "pe Name=\"Student\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http:/" +
                "/schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"name\" Type=" +
                "\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProp" +
                "erty Name=\"Marks\" Relationship=\"WSSPAAModel.FK_Marks_Student\" ToRole=\"Marks\" Fro" +
                "mRole=\"Students\" /></EntityType><Association Name=\"FK_Marks_Student\"><End Type=\"" +
                "WSSPAAModel.Student\" Role=\"Students\" Multiplicity=\"1\" /><End Type=\"WSSPAAModel.M" +
                "ark\" Role=\"Marks\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Stu" +
                "dents\"><PropertyRef Name=\"id\" /></Principal><Dependent Role=\"Marks\"><PropertyRef" +
                " Name=\"id\" /></Dependent></ReferentialConstraint></Association></Schema><Schema " +
                "Namespace=\"Lab6Service\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><En" +
                "tityContainer Name=\"WSSPAAEntities1\" m:IsDefaultEntityContainer=\"true\"><EntitySe" +
                "t Name=\"Marks\" EntityType=\"WSSPAAModel.Mark\" /><EntitySet Name=\"Students\" Entity" +
                "Type=\"WSSPAAModel.Student\" /><AssociationSet Name=\"FK_Marks_Student\" Association" +
                "=\"WSSPAAModel.FK_Marks_Student\"><End Role=\"Marks\" EntitySet=\"Marks\" /><End Role=" +
                "\"Students\" EntitySet=\"Students\" /></AssociationSet></EntityContainer></Schema></" +
                "edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WSSPAAModel.Mark in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// mark1
    /// subject
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id", "mark1", "subject")]
    public partial class Mark
    {
        /// <summary>
        /// Create a new Mark object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="subject">Initial value of subject.</param>
        /// <param name="mark1">Initial value of mark1.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Mark CreateMark(int ID, string subject, int mark1)
        {
            Mark mark = new Mark();
            mark.id = ID;
            mark.subject = subject;
            mark.mark1 = mark1;
            return mark;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property subject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string subject
        {
            get
            {
                return this._subject;
            }
            set
            {
                this.OnsubjectChanging(value);
                this._subject = value;
                this.OnsubjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _subject;
        partial void OnsubjectChanging(string value);
        partial void OnsubjectChanged();
        /// <summary>
        /// There are no comments for Property mark1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int mark1
        {
            get
            {
                return this._mark1;
            }
            set
            {
                this.Onmark1Changing(value);
                this._mark1 = value;
                this.Onmark1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _mark1;
        partial void Onmark1Changing(int value);
        partial void Onmark1Changed();
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this._Student = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Student _Student;
    }
    /// <summary>
    /// There are no comments for WSSPAAModel.Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Student
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Student CreateStudent(int ID)
        {
            Student student = new Student();
            student.id = ID;
            return student;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Marks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Mark> Marks
        {
            get
            {
                return this._Marks;
            }
            set
            {
                if ((value != null))
                {
                    this._Marks = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Mark> _Marks = new global::System.Collections.ObjectModel.Collection<Mark>();
    }
}
