//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFeed")]
    public interface IFeed {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeed/GetStudentNotes", ReplyAction="http://tempuri.org/IFeed/GetStudentNotesResponse")]
        System.ServiceModel.Syndication.SyndicationFeedFormatter GetStudentNotes(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeed/GetStudentNotes", ReplyAction="http://tempuri.org/IFeed/GetStudentNotesResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Syndication.SyndicationFeedFormatter> GetStudentNotesAsync(string studentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeedChannel : Lab7Client.ServiceReference1.IFeed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedClient : System.ServiceModel.ClientBase<Lab7Client.ServiceReference1.IFeed>, Lab7Client.ServiceReference1.IFeed {
        
        public FeedClient() {
        }
        
        public FeedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Syndication.SyndicationFeedFormatter GetStudentNotes(string studentId) {
            return base.Channel.GetStudentNotes(studentId);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Syndication.SyndicationFeedFormatter> GetStudentNotesAsync(string studentId) {
            return base.Channel.GetStudentNotesAsync(studentId);
        }
    }
}
